### ISSUE TITLE
Question about `constEq` in `Server.Internal.JWT. jwtAuthCheck`

### ISSUE THREAD

**Issue by Gosha** [haskell-servant/servant-auth#159]
Why is [Data.ByteArray.constEq](https://hackage.haskell.org/package/memory-0.15.0/docs/Data-ByteArray.html#v:constEq) used here when `ByteString` has an `Eq` instance?
https://github.com/haskell-servant/servant-auth/blob/cc8084dc9df98c7273cb977855c1aa5e7a6b75a3/servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs#L55

Is there some kind of security risk because of timing if not all characters are checked?

**Comment by domenkozar** [comment]
yes

**Comment by Gosha** [comment]
Okay. I see the reasoning behind avoiding timing attacks. But I'm not sure I understand how it would make a difference on comparing `"Bearer "` to `"Bearer "`.

Am I missing something?

Not trying to nit-pick or argue that it should be changed. Just interested!

**Comment by domenkozar** [comment]
That's also not clear to me :) maybe @jkarni was just conservative.

**Comment by jkarni** [comment]
You are all right that it's not necessary. `"Bearer "` is not a secret string. Still not sure if it's worth changing (especially since to my mind having a few constEq sprinkled around the code might remind people who touch to think whether that's the equality they should be using; but mostly because it doesn't seem worth the - very minimal - effort). 

Closing, but reopen if you think there's something to be done!
