### ISSUE TITLE
Document how this package relates to Servant.API.Experimental.Auth and servant's BasicAuth

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell-servant/servant-auth#2]
It could be easier to evaluate this package if some pros and cons were described in the README.

**Comment by jkarni** [comment]
Thanks for the feedback. The behavior of both should be the same, and the only advantage comes when you want alternative authentication methods as well. So if you're *just* using `BasicAuth`, I'd say stick to the one in `servant`.

Is there any place you think would be most appropriate to say this?

**Comment by nmdanny** [comment]
I agree, a comparison on the readme would be nice.

Right now servant also supports generalized auth, so using token authentication is also easy. 
From my brief understanding, the benefits of this library are:
- Allows you to inspect the reason authenticated failed (and consequently choose whether to throw a certain error, do logging etc). 

  However, this can be replicated with Servant's GeneralizedAuth if you simply use `AuthResult User`(or another type of your choosing) instead of using `User` directly as `AuthServerData` type instance and within `AuthHandler`
- Supports multiple auth schemes per api/route.

  You could replicate this within your own AuthHandler, but it wouldn't be explicit in the type level.
- Cookie stuff which I haven't checked (Personally I'm using JWTs passed via header to avoid CSRF)

Wondering what other benefits this library has.

**Comment by jkarni** [comment]
`GeneralizedAuth` is too opaque; it says nothing at all, at the type level, about what the authentication scheme is. This is a deviation from the `servant` philosophy, one which this library "corrects." The obvious advantages are that we can have sensible `servant-client`, `servant-swagger`, `servant-docs` etc. instances that actually accord with the authentication scheme you provided.

Additionally, this library provides a lot of functionality for common authentication schemes and needs out of the box. Cookies are an example. JWTs another. Certainly you could implement these with `GeneralizedAuth`, but here for the most part you don't have to.

**Comment by domenkozar** [comment]
Upstream issue: https://github.com/haskell-servant/servant/issues/805

**Comment by domenkozar** [comment]
Things to document:

- getting started with BasicAuth
- since everything is JWT based, getting started with JWT + BasicAuth

**Comment by domenkozar** [comment]
I've started deprecation work of the two mentioned APIs in https://github.com/haskell-servant/servant/pull/1074 and corresponding issue is for the migration of servant-auth into servant.

I'm closing this one as #64 already exists on servant-auth side.
