### ISSUE TITLE
Contents of CSRF tokens not being checked?

### ISSUE THREAD

**Issue by bts** [haskell-servant/servant-auth#30]
Is it intentional that the contents of the CSRF token seem to not be checked for any cryptographic properties, but only that the two values (in the header, and in the cookie) match? maybe per https://www.owasp.org/index.php/CSRF_Prevention_Cheat_Sheet#Protecting_REST_Services:_Use_of_Custom_Request_Headers?

This request succeeds for any token value:

```
curl -v -H "X-XSRF-TOKEN: foo" -H "Cookie: session=session_goes_here; XSRF-TOKEN=foo" -H "Accept: application/vnd.api+json" "http://localhost:3000/check"
```

If this intentional and if this suffices to protect against CSRF, maybe we shouldn't bother with #27 or even CSRF tokens at all? and instead just require browsers to set the header `X-Requested-With: XMLHttpRequest` as suggested in the owasp link above.

**Comment by jkarni** [comment]
It is intentional. The idea is to only have it be a double-submit token (though this gets called different things in different places, I think). 

The reason I didn't go with `X-Requested-With` is that it seems like this is somewhat safer (only if SOP breaks *both* when reading *and* setting the cookie can it be compromised), and also extends more nicely to non-AJAX calls.

**Comment by jkarni** [comment]
Can I close this? (Though I do feel like I should document better some of the choices...)

**Comment by 3noch** [comment]
I think it would be good to offer multiple choices for CSRF handling. In particular, I could see wanting to use this in combination with checking the Origin and Referer headers.

**Comment by domenkozar** [comment]
I think we can close this, extensible CSRF handling is now part of #55
