### ISSUE TITLE
functions for reading and writing keys

### ISSUE THREAD

**Issue by mwotton** [haskell-servant/servant-auth#35]
first off, kudos! it was surprisingly easy to add auth to my app with this.

Now that i want to push it into prod, i need some way to not recreate the key every time i restart the process. is there an approved way to do that? should i consider Jose.Crypto as part of the public api?

**Comment by jkarni** [comment]
Thanks for the kind words!

Yeah, that could have been clearer in the README. You can use the `From/ToJSON` instances for JWK and store it in a file somewhere (with due care to keep it safe). 

I don't entirely want to say `Jose.Crypto` is part of the public API yet, since there are some issues with partial functions in that package that can in some circumstances land you in trouble with `servant-auth` (not trouble as in "insecure", but trouble as in "all requests fail"). For example, I think using `fromRSA` to generate `JWK` will not work. 

Hopefully `From/ToJSON` is enough for now, but I'll leave the issue open for documentation and possibly other helper functions (such as a version of `fromRSA` that we can use)?

**Comment by mwotton** [comment]
Json serialisability is good enough for me :)

On Fri, Mar 10, 2017, 4:51 PM Julian Arni <notifications@github.com> wrote:

Thanks for the kind words!

Yeah, that could have been clearer in the README. You can use the
From/ToJSON instances for JWK and store it in a file somewhere (with due
care to keep it safe).

I don't entirely want to say Jose.Crypto is part of the public API yet,
since there are some issues with partial functions in that package that can
in some circumstances land you in trouble with servant-auth (not trouble as
in "insecure", but trouble as in "all requests fail"). For example, I think
using fromRSA to generate JWK will not work.

Hopefully From/ToJSON is enough for now, but I'll leave the issue open for
documentation and possibly other helper functions (such as a version of
fromRSA that we can use)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/plow-technologies/servant-auth/issues/35#issuecomment-285794453>,
or mute the thread

**Comment by mschristiansen** [comment]
Took a bit of digging around to come up with these functions.

```haskell
import Prelude hiding (writeFile, readFile)
import Crypto.Random (MonadRandom, getRandomBytes)
import Crypto.JOSE.JWK (JWK, fromOctets)
import Data.ByteString (ByteString, writeFile, readFile)

generateSecret :: MonadRandom m => m ByteString
generateSecret = getRandomBytes 256

fromSecret :: ByteString -> JWK
fromSecret = fromOctets

writeKey :: FilePath -> IO ()
writeKey fp = writeFile fp =<< generateSecret

readKey :: FilePath -> IO JWK
readKey fp = fromSecret <$> readFile fp
```
I think they are useful and simple enough that they should be added to the utilities in `servant-auth-server` and happy to create a PR if there is support for that.

The two functions for reading and writing the bytestring don't do much, but otherwise requires import of bytestring module. Might as well include them.

Let me know if there is any concerns like compatibility with JOSE that I've overlooked.
