### ISSUE TITLE
ThrowAll + ServerT

### ISSUE THREAD

**Issue by boj** [haskell-servant/servant-auth#74]
Given an existing stack I've been hacking on without `servant-auth`:

```haskell
newtype AppM a
  = AppM { runAppM :: ReaderT AppContext (LoggingT (WithSeverity Doc) IO) a }
  deriving ( Functor, Applicative, Monad
           , MonadIO, MonadThrow
           , MonadReader AppContext, MonadLog (WithSeverity Doc))
```

And some sub-set of my API where I try to include `servant-auth`:

```haskell
type ClientApiProtected =
       AssocTerm :> AssociationApi
  :<|> AuthTerm :> AuthApi
  :<|> ManagedAuthTerm :> ManagedAuthApi
  :<|> PermissionTerm :> PermissionApi
  :<|> ServiceTerm :> ServiceApi

type ClientApiUnprotected = UserTerm :> UserApi

type ClientApi =
       (Auth '[JWT] Session :> ClientApiProtected)
  :<|> ClientApiUnprotected


clientApiProtectedServer
  :: AuthResult Session -> ServerT ClientApiProtected AppM
clientApiProtectedServer (Authenticated _) =
       associationApiServer
  :<|> authApiServer
  :<|> managedAuthApiServer
  :<|> permissionApiServer
  :<|> serviceApiServer
clientApiProtectedServer _ = throwAll err401 -- Gah!

clientApiUnprotectedServer
  :: CookieSettings -> JWTSettings -> ServerT ClientApiUnprotected AppM
clientApiUnprotectedServer cs jwts = userApiServer

clientApiServer :: CookieSettings -> JWTSettings -> ServerT ClientApi AppM
clientApiServer cs jwts =
       clientApiProtectedServer
  :<|> clientApiUnprotectedServer cs jwts
```

I end up with the error:

```
    • No instance for (Control.Monad.Error.Class.MonadError
                         ServantErr AppM)
        arising from a use of ‘throwAll’
    • In the expression: throwAll err401
      In an equation for ‘clientApiProtectedServer’:
          clientApiProtectedServer _ = throwAll err401
```

What am I missing here? Attempting to add `MonadError ServantErr` instances to my `AppM` leads me down other rabbit holes, although maybe I am simply doing it wrong.

**Comment by alpmestan** [comment]
You are calling `throwAll` which basically requires that the monad you run your handlers in has an instance for `MonadError ServantErr`, i.e a monad that has a notion of error (à là `Either`, not exceptions) where the error type is `ServantErr`. This is not ideal in terms of design and could be made more flexible in the future, but in the meantime the simplest solution probably is to add an `ExceptT ServantErr` layer in your stack.

**Comment by jkarni** [comment]
> This is not ideal in terms of design and could be made more flexible in the future

Really? How?

**Comment by alpmestan** [comment]
@jkarni Mostly because people seem very, very keen on using "homemade" error types along with `ExceptT` in their monad stacks in most applications. Or, when "more applicable", on relying on exceptions. All of this to say that the `MonadError ServantErr` requirement is not satisfied nor _easily_ satisfiable in most applications that I have seen.

It's not bad, but I think a possibly more flexible requirement to put on the user's monad would be something like:

``` haskell
data  AuthError = Unauthorized -- other things?

class FromAuthError e where
  fromAuthError :: AuthError -> e

instance (FromAuthError e, MonadError e m) => ThrowAll (m a) where
  ...
```

or

``` haskell
data AuthError = Unauthorized -- other things?

class MonadAuth m where -- terrible name
  authError :: AuthError -> m a

instance MonadAuth m => ThrowAll (m a) where
  ...
```

The first approach allows people to use `throwAll` even if they have `ExceptT OurApplicationErrorType` in their stack while the second one doesn't even require `ExceptT` per se. This also has the nice advantage that users get a chance to customize how the error is "rendered" by handling it in their `enter`/`hoistServer`-ed functions.

**Comment by jkarni** [comment]
I'm very much -1 on complicating the codebase and the API and worsening
type inference for a problem that's already solved with hoistServer. It's
not even less code to write a FromAuthError instance than it is to call
hoistServer, so I really don't see the benefit. Am I missing something?

**Comment by boj** [comment]
@alpmestan Thanks for the hint. I ended up with:

```haskell
newtype AppM a
  = AppM
  { runAppM
      :: ReaderT AppContext (ExceptT ServantErr (LoggingT (WithSeverity Doc) IO)) a
  }
  deriving ( Functor, Applicative, Monad
           , MonadIO, MonadThrow, MonadError ServantErr
           , MonadReader AppContext, MonadLog (WithSeverity Doc))
```

And:

```
toHandler :: AppContext -> AppM :~> Handler
toHandler ctx = NT $ \a ->
  (runLogging . runExceptT . flip runReaderT ctx . runAppM) a >>= \case
    Left _  -> throwError err500
    Right r -> return r

server :: CookieSettings -> JWTSettings -> AppContext -> Server Routes
server ccf jcf ctx = enter (toHandler ctx) (routes ccf jcf)
```

**Comment by alpmestan** [comment]
@boj Right, that's exactly what I had in mind. Please allow me to point you to the ongoing cookbook effort, in case you want to illustrate your problem and the solution in a simple example: https://github.com/haskell-servant/servant/pull/867 -- this should be up on readthedocs soon, so the visibility/discoverability should be pretty decent.

@jkarni Well, this forces to have the "toplevel" (as opposed to individual handlers or groups of them) in `Handler`, while servant currently allows you to `hoistServer` at the very very end and define even your "root" server in a custom monad. My two suggestions are just two trivial ways to allow throwAll to be used in such cases as well. There might be nicer alternatives, but I do think the current requirement doesn't really reflect the needs of `throwAll`, or rather how it's used in servant-auth, and how applications want to use it. This `MonadExcept ServantErr` constraint is a rather arbitrary choice that we usually do not make, that's why I suggested variations on it.

**Comment by boj** [comment]
@alpmestan I'm kind of running into the problem you are mentioning. I'd really like to eliminate the `ExceptT` from the top of my stack, but not sure how due to the `ThrowAll`. Is that currently possible at all in servant 0.12?

**Comment by boj** [comment]
Ah, it turns out it was simple.

```haskell
newtype AppT a
  = AppT { runAppT :: ReaderT AppContext Handler a }
  deriving ( Functor, Applicative, Monad
           , MonadIO, MonadThrow, MonadError ServantErr
           , MonadReader AppContext
           )
```

```haskell
toHandler :: AppContext -> AppT a -> Handler a
toHandler ctx = flip runReaderT ctx . runAppT
```

That feels much cleaner.

**Comment by boj** [comment]
I was able to boil it down to this:

```haskell
newtype AppT a
  = AppT { runAppT :: ReaderT AppContext Handler a }
  deriving ( Functor, Applicative, Monad
           , MonadIO, MonadThrow, MonadError ServantErr
           , MonadReader AppContext
           )
```

```haskell
toHandler :: AppContext -> AppT a -> Handler a
toHandler ctx = flip runReaderT ctx . runAppT
```

But then I see these overlapping instances I don't know how to deal with due to the `ThrowAll`.

```
    • Overlapping instances for ThrowAll
                                  (m [Models.Admin.JSON.AdminReadable])
        arising from a use of ‘throwAll’
      Matching instances:
        instance [overlappable] Control.Monad.Error.Class.MonadError
                                  ServantErr m =>
                                ThrowAll (m a)
          -- Defined in ‘Servant.Auth.Server.Internal.ThrowAll’
        instance (ThrowAll a, ThrowAll b) => ThrowAll (a :<|> b)
          -- Defined in ‘Servant.Auth.Server.Internal.ThrowAll’
        instance [overlapping] ThrowAll b => ThrowAll (a -> b)
          -- Defined in ‘Servant.Auth.Server.Internal.ThrowAll’
      (The choice depends on the instantiation of ‘m’
       To pick the first instance above, use IncoherentInstances
       when compiling the other instance declarations)
    • In the expression: throwAll err401
      In an equation for ‘adminApiProtectedServer’:
          adminApiProtectedServer _ = throwAll err401
```
