### ISSUE TITLE
The "WWW-Authenticate" header

### ISSUE THREAD

**Issue by defanor** [haskell-servant/servant-auth#75]
When `Servant.Auth.Server.BasicAuth` is used, `Servant.Auth` doesn't
send the `WWW-Authenticate` header by itself, leaving it to a user. I
see the `wwwAuthenticatedErr` function in
`Servant.Auth.Server.Internal.BasicAuth`, but haven't found it being
exported from non-internal modules, and it is confusing overall: is it
intended for use by a user?

**Comment by jkarni** [comment]
Hm. The issue is that `servant-auth` is designed to allow multiple authentication schemes for the same endpoints. So e.g. you could authenticate with basic auth, or tokens, or cookies, etc. Automatically sending, on failed authentication, a `WWW-Authenticate` header could result in confusing behavior. For example, you might have supported basic auth for easy `curl` access, but intended something else (cookies) for browsers.  

That's why I thought to leave `wwwAuthenticated` for the user to use. But you're absolutely right it should be exported. Do you want to send a PR?

(And if you have any thoughts on how to make things easier and less confusing, do let me know!)

**Comment by defanor** [comment]
Here's a PR, with an annotation edit at once -- should be clearer this
way.
